<datalist id="school-options">
  <option value="Abra State Institute of Science and Technology">
  <option value="Apayao State College">
  <option value="Baguio Central University">
  <option value="Baguio City National High School">
  <option value="Benguet State University">
  <option value="Cordillera Career Development College">
  <option value="Cordillera Regional Science High School">
  <option value="Easter College">
  <option value="Ifugao Provincial Science High School">
  <option value="Ifugao State University">
  <option value="Kalinga State University">
  <option value="Mountain Province State Polytechnic College">
  <option value="Philippine Science High School - Cordillera Administrative Region Campus">
  <option value="Pines City Colleges">
  <option value="Saint Louis University">
  <option value="University of Baguio">
  <option value="University of the Cordilleras">
  <option value="University of the Philippines Baguio">
</datalist>